version: '3.8'

services:
  web:
    build: .
    ports:
      - "9000:80"
    volumes:
      - ./src:/var/www/html
      - ./apache/000-default.conf:/etc/apache2/sites-available/000-default.conf
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=task_manager
      - DB_USER=task_user
      - DB_PASS=task_password
    networks:
      - task-network

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=task_manager
      - MYSQL_USER=task_user
      - MYSQL_PASSWORD=task_password
      - MYSQL_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - task-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      - PMA_HOST=db
      - PMA_USER=task_user
      - PMA_PASSWORD=task_password
    depends_on:
      - db
    networks:
      - task-network

volumes:
  mysql_data:

networks:
  task-network:
    driver: bridge 